//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck_issue_detais
    {
        public int Id { get; set; }
        public string ck_issue_code { get; set; }
        public Nullable<int> ck_item_id { get; set; }
        public string ck_item_code { get; set; }
        public string ck_item_desc { get; set; }
        public Nullable<int> ck_item_unit_id { get; set; }
        public Nullable<decimal> qty_issued { get; set; }
        public Nullable<decimal> ck_item_unit_cost { get; set; }
        public Nullable<decimal> ck_item_total_cost { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual ck_item_unit ck_item_unit { get; set; }
        public virtual ck_items ck_items { get; set; }
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
    }
}
