//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck_items
    {
        public int Id { get; set; }
        public Nullable<int> ck_item_code { get; set; }
        public string ck_item_description { get; set; }
        public Nullable<int> ck_unit_id { get; set; }
        public Nullable<decimal> ck_item_unit_cost { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<int> ck_design_qty { get; set; }
    
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
        public virtual ck_units ck_units { get; set; }
    }
}
