//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck_item_cost_history
    {
        public long Id { get; set; }
        public Nullable<int> ck_item_id { get; set; }
        public string ck_item_code { get; set; }
        public string ck_item_description { get; set; }
        public Nullable<int> ord { get; set; }
        public Nullable<decimal> prev_cost { get; set; }
        public Nullable<decimal> curr_cost { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual ck_users ck_users { get; set; }
        public virtual ck_items ck_items { get; set; }
    }
}
