//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck_issue_master
    {
        public long Id { get; set; }
        public string ck_issue_code { get; set; }
        public Nullable<System.DateTime> ck_issue_date { get; set; }
        public string branch_order_no { get; set; }
        public Nullable<System.DateTime> branch_order_date { get; set; }
        public Nullable<int> issue_to_site_id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
        public virtual site site { get; set; }
    }
}
