//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck_stock_trans
    {
        public long Id { get; set; }
        public Nullable<int> ck_item_id { get; set; }
        public string ck_item_code { get; set; }
        public string ck_item_desc { get; set; }
        public string trans_ref_no { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<System.DateTime> prod_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<int> ck_unit_id { get; set; }
        public string ck_unit_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string trans_type { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<int> trans_from { get; set; }
        public Nullable<int> trans_to { get; set; }
        public Nullable<int> reason_id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual reason_codes reason_codes { get; set; }
        public virtual ck_units ck_units { get; set; }
        public virtual site site { get; set; }
        public virtual site site1 { get; set; }
    }
}
