//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ckwh_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ckwh_items()
        {
            this.ck_item_details = new HashSet<ck_item_details>();
            this.ckwh_item_unit = new HashSet<ckwh_item_unit>();
            this.order_details = new HashSet<order_details>();
            this.receipt_details = new HashSet<receipt_details>();
            this.transaction_details = new HashSet<transaction_details>();
        }
    
        public int Id { get; set; }
        public string wh_item_code { get; set; }
        public string wh_item_description { get; set; }
        public Nullable<int> wh_category_id { get; set; }
        public string wh_category_description { get; set; }
        public Nullable<int> wh_unit_id { get; set; }
        public string wh_unit_description { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<decimal> ck_qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ck_item_details> ck_item_details { get; set; }
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
        public virtual ckwh_category ckwh_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ckwh_item_unit> ckwh_item_unit { get; set; }
        public virtual site site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receipt_details> receipt_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_details> transaction_details { get; set; }
    }
}
