//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_table
    {
        public string SourceTable { get; set; }
        public int LastLoadID { get; set; }
        public System.DateTime LastLoadDate { get; set; }
        public int RowsInserted { get; set; }
    }
}
