//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt_details
    {
        public int Id { get; set; }
        public Nullable<int> receipt_id { get; set; }
        public string receipt_no { get; set; }
        public Nullable<int> wh_item_id { get; set; }
        public Nullable<int> wh_item_unit_id { get; set; }
        public Nullable<decimal> qty_ordered { get; set; }
        public Nullable<decimal> qty_received { get; set; }
        public Nullable<decimal> qyt_returned { get; set; }
        public Nullable<decimal> wh_item_unit_cost { get; set; }
        public Nullable<decimal> wh_item_ext_cost { get; set; }
        public string remarks { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> active { get; set; }
        public string wh_item_code { get; set; }
        public string wh_item_description { get; set; }
        public string ck_unit_description { get; set; }
    
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
        public virtual ckwh_items ckwh_items { get; set; }
        public virtual receipt receipt { get; set; }
        public virtual wh_item_unit wh_item_unit { get; set; }
    }
}
