//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Item_QTY
    {
        public string ITEMNMBR { get; set; }
        public string ITEMDESC { get; set; }
        public string ITMSHNAM { get; set; }
        public decimal CURRCOST { get; set; }
        public string ITMCLSCD { get; set; }
        public string USCATVLS_1 { get; set; }
        public string LOCNCODE { get; set; }
        public decimal QTYONHND { get; set; }
        public decimal ATYALLOC { get; set; }
        public Nullable<decimal> QTYAVBLE { get; set; }
        public string UOMSCHDL { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public System.DateTime MODIFDT { get; set; }
    }
}
