//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipndipInventory.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_delivery_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_delivery_master()
        {
            this.wh_delivery_details = new HashSet<wh_delivery_details>();
        }
    
        public long Id { get; set; }
        public Nullable<long> order_id { get; set; }
        public string order_no { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<int> order_from_site_id { get; set; }
        public Nullable<int> order_to_site_id { get; set; }
        public string order_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ck_users ck_users { get; set; }
        public virtual ck_users ck_users1 { get; set; }
        public virtual order order { get; set; }
        public virtual site site { get; set; }
        public virtual site site1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_delivery_details> wh_delivery_details { get; set; }
    }
}
